# Generated by Django 4.2.5 on 2024-01-16 19:57

from django.db import migrations, models
import flashcards.models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(default='img/flashcards/default.jpg', upload_to=flashcards.models.flashcard_image_src),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='img/profile/default.jpg', upload_to=flashcards.models.profile_pic_src),
        ),
    ]
