# Generated by Django 4.2.5 on 2024-01-16 20:08

from django.db import migrations, models
import flashcards.models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_flashcard_image_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(default='flashcards/static/img/flashcards/default.jpg', upload_to=flashcards.models.flashcard_image_src),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='flashcards/static/img/users/default.jpg', upload_to=flashcards.models.profile_pic_src),
        ),
    ]
