# Generated by Django 4.2.5 on 2024-01-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_flashcard_image_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='last_studied',
            field=models.DateTimeField(default=None),
        ),
    ]
