# Generated by Django 4.2.5 on 2024-01-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_stats_need_practice_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='last_studied',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='percent_learned',
            field=models.FloatField(default=100.0),
        ),
    ]
