# Generated by Django 4.2.5 on 2024-01-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_alter_stats_last_studied_alter_stats_percent_learned'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proficiency',
            unique_together={('user', 'flashcard')},
        ),
    ]
