# Generated by Django 4.2.5 on 2024-01-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0010_alter_proficiency_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='percent_learned',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
