# Generated by Django 4.2.5 on 2024-01-18 19:24

from django.db import migrations, models
import flashcards.models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_alter_stats_percent_learned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='img/users/default.jpg', null=True, upload_to=flashcards.models.profile_pic_src),
        ),
    ]
